version: '2'
services:
  web:
    build: .
    image: sources
    restart: always
    command: yarn start
    ports:
    - "3000:3000"
    depends_on:
    - database
    environment:
    - DATABASE_USER=sources
    - DATABASE_PASSWORD=sources
    - DATABASE_HOST=database
  database:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
    - POSTGRES_USER=sources
    - POSTGRES_PASSWORD=sources
    - POSTGRES_DB=sources
